[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.90"
license = "Apache-2.0"
authors = ["Ikuma Yamashita"]
repository = "https://github.com/46ki75/mcp-rust-docs"

[workspace.dependencies]
rmcp = { version = "1.7", features = [
    "server",
    "macros",
    "transport-io",
    "transport-streamable-http-server",
    "schemars",
] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "signal",
    "io-std",
] }
tokio-util = { version = "0.7", features = ["rt"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "1"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }
fast_html2md = "0.0.62"
axum = "0.8"
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2"
wiremock = "0.6"
ruzstd = { version = "0.8", default-features = false, features = ["std"] }
rustdoc-types = "0.57"

[workspace.lints.clippy]
unwrap_used = "deny"
